# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b914685571b21c7b37578ea928d8dd1c"
name = "practice"
handle = "practice-114"
application_url = "https://landing-walked-incorrect-sean.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-testing-dev1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_checkouts,read_discounts,read_price_rules,read_products,read_script_tags,read_shipping,read_themes,unauthenticated_read_customer_tags,unauthenticated_read_customers,unauthenticated_read_product_listings,unauthenticated_read_selling_plans,write_checkouts,write_discounts,write_price_rules,write_products,write_script_tags,write_shipping,write_themes"

[auth]
redirect_urls = [
  "https://landing-walked-incorrect-sean.trycloudflare.com/auth/callback",
  "https://landing-walked-incorrect-sean.trycloudflare.com/auth/shopify/callback",
  "https://landing-walked-incorrect-sean.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
