# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b914685571b21c7b37578ea928d8dd1c"
name = "practice"
handle = "practice-114"
application_url = "https://soup-description-internet-fa.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-testing-dev1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_script_tags,read_themes,write_products,write_script_tags,write_themes"

[auth]
redirect_urls = [
  "https://soup-description-internet-fa.trycloudflare.com/auth/callback",
  "https://soup-description-internet-fa.trycloudflare.com/auth/shopify/callback",
  "https://soup-description-internet-fa.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
